(define (problem strips_log_x_23)
   (:domain logistics_strips)
   (:objects package21 package20 package19 package18 package17
             package16 package15 package14 package13 package12 package11
             package10 package9 package8 package7 package6 package5 package4
             package3 package2 package1 city8 city7 city6 city5 city4 city3
             city2 city1 truck28 truck27 truck26 truck25 truck24 truck23
             truck22 truck21 truck20 truck19 truck18 truck17 truck16
             truck15 truck14 truck13 truck12 truck11 truck10 truck9 truck8
             truck7 truck6 truck5 truck4 truck3 truck2 truck1 plane4 plane3
             plane2 plane1 city8_1 city7_1 city6_1 city5_1 city4_1 city3_1
             city2_1 city1_1 city8_2 city7_2 city6_2 city5_2 city4_2
             city3_2 city2_2 city1_2)
   (:init (obj package21)
          (obj package20)
          (obj package19)
          (obj package18)
          (obj package17)
          (obj package16)
          (obj package15)
          (obj package14)
          (obj package13)
          (obj package12)
          (obj package11)
          (obj package10)
          (obj package9)
          (obj package8)
          (obj package7)
          (obj package6)
          (obj package5)
          (obj package4)
          (obj package3)
          (obj package2)
          (obj package1)
          (city city8)
          (city city7)
          (city city6)
          (city city5)
          (city city4)
          (city city3)
          (city city2)
          (city city1)
          (truck truck28)
          (truck truck27)
          (truck truck26)
          (truck truck25)
          (truck truck24)
          (truck truck23)
          (truck truck22)
          (truck truck21)
          (truck truck20)
          (truck truck19)
          (truck truck18)
          (truck truck17)
          (truck truck16)
          (truck truck15)
          (truck truck14)
          (truck truck13)
          (truck truck12)
          (truck truck11)
          (truck truck10)
          (truck truck9)
          (truck truck8)
          (truck truck7)
          (truck truck6)
          (truck truck5)
          (truck truck4)
          (truck truck3)
          (truck truck2)
          (truck truck1)
          (airplane plane4)
          (airplane plane3)
          (airplane plane2)
          (airplane plane1)
          (location city8_1)
          (location city7_1)
          (location city6_1)
          (location city5_1)
          (location city4_1)
          (location city3_1)
          (location city2_1)
          (location city1_1)
          (airport city8_2)
          (location city8_2)
          (airport city7_2)
          (location city7_2)
          (airport city6_2)
          (location city6_2)
          (airport city5_2)
          (location city5_2)
          (airport city4_2)
          (location city4_2)
          (airport city3_2)
          (location city3_2)
          (airport city2_2)
          (location city2_2)
          (airport city1_2)
          (location city1_2)
          (in_city city8_2 city8)
          (in_city city8_1 city8)
          (in_city city7_2 city7)
          (in_city city7_1 city7)
          (in_city city6_2 city6)
          (in_city city6_1 city6)
          (in_city city5_2 city5)
          (in_city city5_1 city5)
          (in_city city4_2 city4)
          (in_city city4_1 city4)
          (in_city city3_2 city3)
          (in_city city3_1 city3)
          (in_city city2_2 city2)
          (in_city city2_1 city2)
          (in_city city1_2 city1)
          (in_city city1_1 city1)
          (at plane4 city5_2)
          (at plane3 city7_2)
          (at plane2 city3_2)
          (at plane1 city1_2)
          (at truck28 city8_1)
          (at truck27 city7_1)
          (at truck26 city6_1)
          (at truck25 city5_1)
          (at truck24 city4_1)
          (at truck23 city3_1)
          (at truck22 city2_1)
          (at truck21 city1_1)
          (at truck20 city2_2)
          (at truck19 city1_1)
          (at truck18 city2_1)
          (at truck17 city7_1)
          (at truck16 city2_2)
          (at truck15 city3_1)
          (at truck14 city5_2)
          (at truck13 city5_1)
          (at truck12 city5_2)
          (at truck11 city6_2)
          (at truck10 city2_2)
          (at truck9 city2_2)
          (at truck8 city1_1)
          (at truck7 city1_1)
          (at truck6 city4_1)
          (at truck5 city6_2)
          (at truck4 city4_1)
          (at truck3 city4_1)
          (at truck2 city2_1)
          (at truck1 city5_2)
          (at package21 city3_1)
          (at package20 city3_1)
          (at package19 city8_1)
          (at package18 city5_1)
          (at package17 city1_2)
          (at package16 city6_1)
          (at package15 city7_2)
          (at package14 city4_2)
          (at package13 city1_1)
          (at package12 city1_2)
          (at package11 city1_2)
          (at package10 city1_2)
          (at package9 city1_1)
          (at package8 city6_1)
          (at package7 city1_1)
          (at package6 city7_1)
          (at package5 city3_1)
          (at package4 city3_2)
          (at package3 city3_1)
          (at package2 city1_2)
          (at package1 city1_1))
   (:goal (and (at package21 city5_2)
               (at package20 city2_2)
               (at package19 city2_1)
               (at package18 city2_2)
               (at package17 city6_1)
               (at package16 city1_1)
               (at package15 city3_2)
               (at package14 city3_1)
               (at package13 city6_1)
               (at package12 city8_1)
               (at package11 city1_2)
               (at package10 city4_1)
               (at package9 city7_1)
               (at package8 city2_1)
               (at package7 city3_2)
               (at package6 city2_2)
               (at package5 city8_2)
               (at package4 city8_2)
               (at package3 city1_2)
               (at package2 city6_2)
               (at package1 city8_2))))