(define (problem strips_log_x_15)
   (:domain logistics_strips)
   (:objects package23 package22 package21 package20 package19
             package18 package17 package16 package15 package14 package13
             package12 package11 package10 package9 package8 package7
             package6 package5 package4 package3 package2 package1 city3
             city2 city1 truck5 truck4 truck3 truck2 truck1 plane7 plane6
             plane5 plane4 plane3 plane2 plane1 city3_5 city3_4 city3_3
             city3_2 city3_1 city2_5 city2_4 city2_3 city2_2 city2_1
             city1_5 city1_4 city1_3 city1_2 city1_1 city3_6 city2_6
             city1_6)
   (:init (obj package23)
          (obj package22)
          (obj package21)
          (obj package20)
          (obj package19)
          (obj package18)
          (obj package17)
          (obj package16)
          (obj package15)
          (obj package14)
          (obj package13)
          (obj package12)
          (obj package11)
          (obj package10)
          (obj package9)
          (obj package8)
          (obj package7)
          (obj package6)
          (obj package5)
          (obj package4)
          (obj package3)
          (obj package2)
          (obj package1)
          (city city3)
          (city city2)
          (city city1)
          (truck truck5)
          (truck truck4)
          (truck truck3)
          (truck truck2)
          (truck truck1)
          (airplane plane7)
          (airplane plane6)
          (airplane plane5)
          (airplane plane4)
          (airplane plane3)
          (airplane plane2)
          (airplane plane1)
          (location city3_5)
          (location city3_4)
          (location city3_3)
          (location city3_2)
          (location city3_1)
          (location city2_5)
          (location city2_4)
          (location city2_3)
          (location city2_2)
          (location city2_1)
          (location city1_5)
          (location city1_4)
          (location city1_3)
          (location city1_2)
          (location city1_1)
          (airport city3_6)
          (location city3_6)
          (airport city2_6)
          (location city2_6)
          (airport city1_6)
          (location city1_6)
          (in_city city3_6 city3)
          (in_city city3_5 city3)
          (in_city city3_4 city3)
          (in_city city3_3 city3)
          (in_city city3_2 city3)
          (in_city city3_1 city3)
          (in_city city2_6 city2)
          (in_city city2_5 city2)
          (in_city city2_4 city2)
          (in_city city2_3 city2)
          (in_city city2_2 city2)
          (in_city city2_1 city2)
          (in_city city1_6 city1)
          (in_city city1_5 city1)
          (in_city city1_4 city1)
          (in_city city1_3 city1)
          (in_city city1_2 city1)
          (in_city city1_1 city1)
          (at plane7 city1_6)
          (at plane6 city2_6)
          (at plane5 city1_6)
          (at plane4 city1_6)
          (at plane3 city3_6)
          (at plane2 city1_6)
          (at plane1 city2_6)
          (at truck5 city3_4)
          (at truck4 city2_3)
          (at truck3 city1_5)
          (at truck2 city1_3)
          (at truck1 city1_6)
          (at package23 city1_5)
          (at package22 city1_5)
          (at package21 city2_4)
          (at package20 city2_3)
          (at package19 city1_2)
          (at package18 city3_3)
          (at package17 city2_3)
          (at package16 city3_5)
          (at package15 city2_2)
          (at package14 city2_1)
          (at package13 city3_4)
          (at package12 city1_6)
          (at package11 city1_4)
          (at package10 city3_3)
          (at package9 city3_3)
          (at package8 city1_2)
          (at package7 city1_4)
          (at package6 city1_4)
          (at package5 city3_1)
          (at package4 city2_1)
          (at package3 city1_5)
          (at package2 city3_3)
          (at package1 city1_2))
   (:goal (and (at package23 city2_3)
               (at package22 city1_5)
               (at package21 city1_6)
               (at package20 city1_1)
               (at package19 city1_3)
               (at package18 city1_3)
               (at package17 city1_5)
               (at package16 city1_1)
               (at package15 city3_3)
               (at package14 city1_5)
               (at package13 city2_5)
               (at package12 city3_2)
               (at package11 city2_6)
               (at package10 city1_6))))