(define (problem strips_log_x_9)
   (:domain logistics_strips)
   (:objects package12 package11 package10 package9 package8
             package7 package6 package5 package4 package3 package2 package1
             city11 city10 city9 city8 city7 city6 city5 city4 city3 city2
             city1 truck28 truck27 truck26 truck25 truck24 truck23
             truck22 truck21 truck20 truck19 truck18 truck17 truck16
             truck15 truck14 truck13 truck12 truck11 truck10 truck9 truck8
             truck7 truck6 truck5 truck4 truck3 truck2 truck1 plane4 plane3
             plane2 plane1 city11_5 city11_4 city11_3 city11_2 city11_1
             city10_5 city10_4 city10_3 city10_2 city10_1 city9_5 city9_4
             city9_3 city9_2 city9_1 city8_5 city8_4 city8_3 city8_2
             city8_1 city7_5 city7_4 city7_3 city7_2 city7_1 city6_5
             city6_4 city6_3 city6_2 city6_1 city5_5 city5_4 city5_3
             city5_2 city5_1 city4_5 city4_4 city4_3 city4_2 city4_1
             city3_5 city3_4 city3_3 city3_2 city3_1 city2_5 city2_4
             city2_3 city2_2 city2_1 city1_5 city1_4 city1_3 city1_2
             city1_1 city11_6 city10_6 city9_6 city8_6 city7_6 city6_6
             city5_6 city4_6 city3_6 city2_6 city1_6)
   (:init (obj package12)
          (obj package11)
          (obj package10)
          (obj package9)
          (obj package8)
          (obj package7)
          (obj package6)
          (obj package5)
          (obj package4)
          (obj package3)
          (obj package2)
          (obj package1)
          (city city11)
          (city city10)
          (city city9)
          (city city8)
          (city city7)
          (city city6)
          (city city5)
          (city city4)
          (city city3)
          (city city2)
          (city city1)
          (truck truck28)
          (truck truck27)
          (truck truck26)
          (truck truck25)
          (truck truck24)
          (truck truck23)
          (truck truck22)
          (truck truck21)
          (truck truck20)
          (truck truck19)
          (truck truck18)
          (truck truck17)
          (truck truck16)
          (truck truck15)
          (truck truck14)
          (truck truck13)
          (truck truck12)
          (truck truck11)
          (truck truck10)
          (truck truck9)
          (truck truck8)
          (truck truck7)
          (truck truck6)
          (truck truck5)
          (truck truck4)
          (truck truck3)
          (truck truck2)
          (truck truck1)
          (airplane plane4)
          (airplane plane3)
          (airplane plane2)
          (airplane plane1)
          (location city11_5)
          (location city11_4)
          (location city11_3)
          (location city11_2)
          (location city11_1)
          (location city10_5)
          (location city10_4)
          (location city10_3)
          (location city10_2)
          (location city10_1)
          (location city9_5)
          (location city9_4)
          (location city9_3)
          (location city9_2)
          (location city9_1)
          (location city8_5)
          (location city8_4)
          (location city8_3)
          (location city8_2)
          (location city8_1)
          (location city7_5)
          (location city7_4)
          (location city7_3)
          (location city7_2)
          (location city7_1)
          (location city6_5)
          (location city6_4)
          (location city6_3)
          (location city6_2)
          (location city6_1)
          (location city5_5)
          (location city5_4)
          (location city5_3)
          (location city5_2)
          (location city5_1)
          (location city4_5)
          (location city4_4)
          (location city4_3)
          (location city4_2)
          (location city4_1)
          (location city3_5)
          (location city3_4)
          (location city3_3)
          (location city3_2)
          (location city3_1)
          (location city2_5)
          (location city2_4)
          (location city2_3)
          (location city2_2)
          (location city2_1)
          (location city1_5)
          (location city1_4)
          (location city1_3)
          (location city1_2)
          (location city1_1)
          (airport city11_6)
          (location city11_6)
          (airport city10_6)
          (location city10_6)
          (airport city9_6)
          (location city9_6)
          (airport city8_6)
          (location city8_6)
          (airport city7_6)
          (location city7_6)
          (airport city6_6)
          (location city6_6)
          (airport city5_6)
          (location city5_6)
          (airport city4_6)
          (location city4_6)
          (airport city3_6)
          (location city3_6)
          (airport city2_6)
          (location city2_6)
          (airport city1_6)
          (location city1_6)
          (in_city city11_6 city11)
          (in_city city11_5 city11)
          (in_city city11_4 city11)
          (in_city city11_3 city11)
          (in_city city11_2 city11)
          (in_city city11_1 city11)
          (in_city city10_6 city10)
          (in_city city10_5 city10)
          (in_city city10_4 city10)
          (in_city city10_3 city10)
          (in_city city10_2 city10)
          (in_city city10_1 city10)
          (in_city city9_6 city9)
          (in_city city9_5 city9)
          (in_city city9_4 city9)
          (in_city city9_3 city9)
          (in_city city9_2 city9)
          (in_city city9_1 city9)
          (in_city city8_6 city8)
          (in_city city8_5 city8)
          (in_city city8_4 city8)
          (in_city city8_3 city8)
          (in_city city8_2 city8)
          (in_city city8_1 city8)
          (in_city city7_6 city7)
          (in_city city7_5 city7)
          (in_city city7_4 city7)
          (in_city city7_3 city7)
          (in_city city7_2 city7)
          (in_city city7_1 city7)
          (in_city city6_6 city6)
          (in_city city6_5 city6)
          (in_city city6_4 city6)
          (in_city city6_3 city6)
          (in_city city6_2 city6)
          (in_city city6_1 city6)
          (in_city city5_6 city5)
          (in_city city5_5 city5)
          (in_city city5_4 city5)
          (in_city city5_3 city5)
          (in_city city5_2 city5)
          (in_city city5_1 city5)
          (in_city city4_6 city4)
          (in_city city4_5 city4)
          (in_city city4_4 city4)
          (in_city city4_3 city4)
          (in_city city4_2 city4)
          (in_city city4_1 city4)
          (in_city city3_6 city3)
          (in_city city3_5 city3)
          (in_city city3_4 city3)
          (in_city city3_3 city3)
          (in_city city3_2 city3)
          (in_city city3_1 city3)
          (in_city city2_6 city2)
          (in_city city2_5 city2)
          (in_city city2_4 city2)
          (in_city city2_3 city2)
          (in_city city2_2 city2)
          (in_city city2_1 city2)
          (in_city city1_6 city1)
          (in_city city1_5 city1)
          (in_city city1_4 city1)
          (in_city city1_3 city1)
          (in_city city1_2 city1)
          (in_city city1_1 city1)
          (at plane4 city5_6)
          (at plane3 city6_6)
          (at plane2 city7_6)
          (at plane1 city10_6)
          (at truck28 city11_2)
          (at truck27 city10_2)
          (at truck26 city9_1)
          (at truck25 city8_2)
          (at truck24 city7_5)
          (at truck23 city6_1)
          (at truck22 city5_2)
          (at truck21 city4_2)
          (at truck20 city3_3)
          (at truck19 city2_1)
          (at truck18 city1_1)
          (at truck17 city7_3)
          (at truck16 city6_3)
          (at truck15 city8_5)
          (at truck14 city11_6)
          (at truck13 city9_6)
          (at truck12 city7_1)
          (at truck11 city8_6)
          (at truck10 city1_1)
          (at truck9 city4_1)
          (at truck8 city2_5)
          (at truck7 city9_1)
          (at truck6 city2_6)
          (at truck5 city8_6)
          (at truck4 city4_1)
          (at truck3 city4_1)
          (at truck2 city8_2)
          (at truck1 city1_5)
          (at package12 city1_2)
          (at package11 city9_1)
          (at package10 city4_6)
          (at package9 city8_4)
          (at package8 city11_5)
          (at package7 city2_4)
          (at package6 city4_1)
          (at package5 city2_6)
          (at package4 city4_4)
          (at package3 city4_5)
          (at package2 city2_6)
          (at package1 city6_6))
   (:goal (and (at package12 city5_4)
               (at package11 city4_1)
               (at package10 city6_2)
               (at package9 city8_4)
               (at package8 city2_3)
               (at package7 city9_6)
               (at package6 city2_4)
               (at package5 city10_3)
               (at package4 city4_4)
               (at package3 city8_1)
               (at package2 city9_2)
               (at package1 city5_1))))