(define (problem blocks_10_2)
(:domain blocks)
(:objects b g e d f h i a c j - block)
(:init (clear j) (clear c) (ontable a) (ontable c) (on j i) (on i h) (on h f)
 (on f d) (on d e) (on e g) (on g b) (on b a) )
(:goal (and (on b e) (on e i) (on i g) (on g h) (on h c) (on c a) (on a f)
            (on f j) (on j d)))
)