(define (problem blocks_6_2)
(:domain blocks)
(:objects e f b d c a - block)
(:init (clear a) (ontable c) (on a d) (on d b) (on b f) (on f e) (on e c)
 (handempty))
(:goal (and (on e f) (on f a) (on a b) (on b c) (on c d)))
)