(define (problem strips_log_x_7)
   (:domain logistics_strips)
   (:objects package10 package9 package8 package7 package6
             package5 package4 package3 package2 package1 city11 city10
             city9 city8 city7 city6 city5 city4 city3 city2 city1 truck11
             truck10 truck9 truck8 truck7 truck6 truck5 truck4 truck3 truck2
             truck1 plane6 plane5 plane4 plane3 plane2 plane1 city11_1
             city10_1 city9_1 city8_1 city7_1 city6_1 city5_1 city4_1
             city3_1 city2_1 city1_1 city11_2 city10_2 city9_2 city8_2
             city7_2 city6_2 city5_2 city4_2 city3_2 city2_2 city1_2)
   (:init (obj package10)
          (obj package9)
          (obj package8)
          (obj package7)
          (obj package6)
          (obj package5)
          (obj package4)
          (obj package3)
          (obj package2)
          (obj package1)
          (city city11)
          (city city10)
          (city city9)
          (city city8)
          (city city7)
          (city city6)
          (city city5)
          (city city4)
          (city city3)
          (city city2)
          (city city1)
          (truck truck11)
          (truck truck10)
          (truck truck9)
          (truck truck8)
          (truck truck7)
          (truck truck6)
          (truck truck5)
          (truck truck4)
          (truck truck3)
          (truck truck2)
          (truck truck1)
          (airplane plane6)
          (airplane plane5)
          (airplane plane4)
          (airplane plane3)
          (airplane plane2)
          (airplane plane1)
          (location city11_1)
          (location city10_1)
          (location city9_1)
          (location city8_1)
          (location city7_1)
          (location city6_1)
          (location city5_1)
          (location city4_1)
          (location city3_1)
          (location city2_1)
          (location city1_1)
          (airport city11_2)
          (location city11_2)
          (airport city10_2)
          (location city10_2)
          (airport city9_2)
          (location city9_2)
          (airport city8_2)
          (location city8_2)
          (airport city7_2)
          (location city7_2)
          (airport city6_2)
          (location city6_2)
          (airport city5_2)
          (location city5_2)
          (airport city4_2)
          (location city4_2)
          (airport city3_2)
          (location city3_2)
          (airport city2_2)
          (location city2_2)
          (airport city1_2)
          (location city1_2)
          (in_city city11_2 city11)
          (in_city city11_1 city11)
          (in_city city10_2 city10)
          (in_city city10_1 city10)
          (in_city city9_2 city9)
          (in_city city9_1 city9)
          (in_city city8_2 city8)
          (in_city city8_1 city8)
          (in_city city7_2 city7)
          (in_city city7_1 city7)
          (in_city city6_2 city6)
          (in_city city6_1 city6)
          (in_city city5_2 city5)
          (in_city city5_1 city5)
          (in_city city4_2 city4)
          (in_city city4_1 city4)
          (in_city city3_2 city3)
          (in_city city3_1 city3)
          (in_city city2_2 city2)
          (in_city city2_1 city2)
          (in_city city1_2 city1)
          (in_city city1_1 city1)
          (at plane6 city2_2)
          (at plane5 city5_2)
          (at plane4 city6_2)
          (at plane3 city9_2)
          (at plane2 city8_2)
          (at plane1 city1_2)
          (at truck11 city11_1)
          (at truck10 city10_1)
          (at truck9 city9_1)
          (at truck8 city8_1)
          (at truck7 city7_1)
          (at truck6 city6_1)
          (at truck5 city5_1)
          (at truck4 city4_1)
          (at truck3 city3_1)
          (at truck2 city2_1)
          (at truck1 city1_1)
          (at package10 city6_2)
          (at package9 city5_2)
          (at package8 city10_2)
          (at package7 city6_2)
          (at package6 city1_2)
          (at package5 city4_1)
          (at package4 city4_2)
          (at package3 city1_2)
          (at package2 city10_2)
          (at package1 city8_1))
   (:goal (and (at package10 city9_1)
               (at package9 city9_2)
               (at package8 city1_2)
               (at package7 city5_1)
               (at package6 city10_2)
               (at package5 city7_1))))