(define (problem log_x_1)
   (:domain logistics)
   (:objects package6 package5 package4 package3 package2 package1
             - package
             city6 city5 city4 city3 city2 city1 - city
             truck6 truck5 truck4 truck3 truck2 truck1 - truck
             plane2 plane1 - airplane
             city6_1 city5_1 city4_1 city3_1 city2_1 city1_1 - location
             city6_2 city5_2 city4_2 city3_2 city2_2 city1_2 - airport)
   (:init (in_city city6_2 city6)
          (in_city city6_1 city6)
          (in_city city5_2 city5)
          (in_city city5_1 city5)
          (in_city city4_2 city4)
          (in_city city4_1 city4)
          (in_city city3_2 city3)
          (in_city city3_1 city3)
          (in_city city2_2 city2)
          (in_city city2_1 city2)
          (in_city city1_2 city1)
          (in_city city1_1 city1)
          (at plane2 city4_2)
          (at plane1 city4_2)
          (at truck6 city6_1)
          (at truck5 city5_1)
          (at truck4 city4_1)
          (at truck3 city3_1)
          (at truck2 city2_1)
          (at truck1 city1_1)
          (at package6 city3_1)
          (at package5 city4_2)
          (at package4 city1_1)
          (at package3 city1_1)
          (at package2 city1_2)
          (at package1 city2_1))
   (:goal (and (at package6 city1_2)
               (at package5 city6_2)
               (at package4 city3_2)
               (at package3 city6_1)
               (at package2 city6_2)
               (at package1 city2_1))))